### ISSUE TITLE
quality level with bitrate not being set to the label

### ISSUE THREAD

**Issue by thienedits** [jfujita/videojs-http-source-selector#4]
I think the problem is the `else if` statement here:
https://github.com/pivotshare/videojs-http-source-selector/blob/1976dc8b15db269c9e25b2546a2a989add001fbe/src/components/SourceMenuButton.js#L103

I think just change it to an `if` statement

**Comment by jfujita** [comment]
@thienedits I'm not sure that'll work.  We're biased towards displaying (vertical) resolution as the label with a fallback to the bitrate where available.  Some source streams may have both ```height``` and ```bitrate``` metadata, which is why the bitrate label assignment takes a back seat to height.  Perhaps an enhancement could be to specify which metadata to bias towards for labeling, eg [bitrate | height]

**Comment by thienedits** [comment]
ah ok that makes sense. thanks.
