### ISSUE TITLE
Video Streams Won't Show Qualities Above 1080p

### ISSUE THREAD

**Issue by PrestonN** [jfujita/videojs-http-source-selector#47]
Hello!

I've been playing around with your plugin and I noticed that the selection of qualities max out at 1080p even though my streams have support for up to 8k.  I was wondering if we could get support for higher quality streams?

I may be interested in tackling this issue myself if time permits.  I wanted to put this issue out here first in case anyone else wants to do it.

**Comment by omarroth** [comment]
Mind providing an example?

**Comment by PrestonN** [comment]
Watching anything on Invidious with DASH enabled should show a good enough example.

https://invidio.us/watch?v=4DKLA7w9eeA

The example video (again with DASH enabled) only shows qualities up to 1080p.  If you watch the same video on YouTube, you'll see that qualities up to 4k are available.

While looking up an example video I did see something else though.

https://invidio.us/watch?v=n-RjGEWW3nk

This video would show 8k as an option most of the time, however I noticed it only maxed out at 1080p periodically.

You can also try loading a video on the [FreeTube Rewrite](https://github.com/FreeTubeApp/FreeTube-Vue) if you're willing to set it up.  The same problem persists there.

**Comment by omarroth** [comment]
Thanks. This is an issue with videojs/http-streaming, not this plugin.

The issue is that http-streaming will filter out streams that are provided in a different container than those it has already encountered or supports (in this case `video/webm` vs `video/mp4`). I believe there were also a couple issues when mixing codecs, although that may be fixed with videojs/http-streaming#617. 

From some quick testing, it's possible to get the desired result by only using a manifest with video/webm along with some changes to http-streaming to force support (e.g. changing [this line](https://github.com/videojs/http-streaming/blob/450ca91ade3c8fd7b96834e811ccd6699daee834/src/source-updater.js#L234) to `video/webm` along with the changes in the linked PR).

The main issue is mixing containers, which may not have an obvious solution (I'm not familiar enough with the project to say).

**Comment by PrestonN** [comment]
Thanks for the info.  I wasn't sure on which project to make the issue on and it seemed like this was the right one.  I guess I was wrong.

It looks like the PR you mentioned got moved to [vhs-utils](https://github.com/videojs/vhs-utils) so I'll take a look at that and see if I can get it working.  I'll take a look at the other suggestions you made as well.

Thanks again!
